export const cardData = [
  { id: 1, image: "babyCapy.jpg" },
  { id: 2, image: "capyEating.jpg" },
  { id: 3, image: "capyLettuce.jpg" },
  { id: 4, image: "capyOrange.jpg" },
  { id: 5, image: "capyRelax.jpg" },
  { id: 6, image: "capyWithBabies.jpg" },
  { id: 7, image: "capyWithBird.jpg" },
  { id: 8, image: "capyWithPups.jpg" },
  { id: 9, image: "albinoCapy.jpeg" },
  { id: 1, image: "babyCapy.jpg" },
  { id: 2, image: "capyEating.jpg" },
  { id: 3, image: "capyLettuce.jpg" },
  { id: 4, image: "capyOrange.jpg" },
  { id: 5, image: "capyRelax.jpg" },
  { id: 6, image: "capyWithBabies.jpg" },
  { id: 7, image: "capyWithBird.jpg" },
  { id: 8, image: "capyWithPups.jpg" },
  { id: 9, image: "albinoCapy.jpeg" },
];
